[".config/nvim"]
type = "git-repo"
url = "git@github.com:williamgoulois/nvim"
refreshPeriod = "168h"

[".config/alacritty/colors"]
type = "git-repo"
url = "git@github.com:eendroroy/alacritty-theme.git"
refreshPeriod = "168h"

[".zprezto"]
type = "git-repo"
url = "git@github.com:sorin-ionescu/prezto.git"
[".zprezto".clone]
args = ["--recursive"]

[".zprezto/contrib"]
type = "git-repo"
url = "git@github.com:belak/prezto-contrib.git"
[".zprezto/contrib".clone]
args = ["--recurse-submodules"]
